name: Run tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - run: npm install --save-dev
        name: Install jest
      - run: npm test
        name: Run unit tests
